### ISSUE TITLE
Non-convergence

### ISSUE THREAD

**Issue by tommorris168** [CRSU-Apps/MetaDTA#18]
If the model doesn't converge there is no warning given to the user.

**Comment by DBSMD** [comment]
I am currently involved in a meta-analysis of the accuracy of diagnostic tests for dementia. For some data sets that MetaDTA analyzed in June, and reported the pooled sensitivity, specificity, and diagnostic odds ratio, the data now can't be analyzed because the analysis "failed to converge". Can someone explain what it is a about a data set that causes this issue? What can I do to correct the problem?

**Comment by tommorris168** [comment]
@DBSMD the failure to converge was happening when you analyzed your data in June as well, you just weren't aware of it because the app didn't notify the user.
You could try running the data through MetaBayesDTA as a next step: http://apps.crsu.org.uk/MetaBayesDTA/
Another option is to download MetaDTA and run it from your computer, where you might get better error messages. Alternatively I could try this step for you if you are willing to send me your data. Unfortunately I can only help if the problem is related to the app rather than there being a fundamental problem with the dataset itself. My e-mail address is tm428@le.ac.uk.
